using DnDSidekick.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DnDSidekick.Data.InitialData
{
    public static class MonsterEnvironsInitialData
    {
        public static readonly string[] DataSeed =
        {
            "1,Forest,Hill",
            "2,Forest",
            "4,Desert,Forest,Grassland,Urban",
            "5,Coastal",
            "6,Forest,Grassland",
            "7,Coastal,Grassland,Hill,Mountain",
            "9,Underdark",
            "10,Grassland,Hill,Mountain,Urban",
            "12,Desert,Forest,Grassland,Hill",
            "13,Desert,Grassland",
            "15,Underwater",
            "16,Arctic,Forest",
            "17,Underwater",
            "18,Swamp,Urban",
            "19,Hill,Swamp,Urban",
            "20,Desert",
            "21,Underwater",
            "23,Desert,Grassland,Hill",
            "25,Arctic,Coastal,Forest,Grassland,Hill,Mountain",
            "26,Desert",
            "27,Desert,Forest,Grassland,Urban",
            "28,Coastal",
            "29,Forest,Swamp,Underdark,Urban",
            "30,Forest,Grassland,Hill",
            "31,Forest,Hill,Urban",
            "32,Desert,Hill,Urban",
            "33,Coastal,Desert,Forest,Grassland,Hill,Swamp",
            "34,Urban",
            "35,Coastal,Desert,Forest,Grassland,Hill,Mountain,Swamp,Underdark,Urban",
            "36,Grassland,Hill",
            "37,Forest,Grassland,Hill",
            "38,Desert,Forest,Swamp,Underwater",
            "39,Urban",
            "40,Forest,Grassland,Hill",
            "41,Forest",
            "42,Forest,Underdark",
            "43,Underdark,Urban",
            "44,Forest,Swamp",
            "45,Coastal,Desert,Forest,Swamp,Underdark",
            "46,Arctic,Forest,Hill",
            "47,Desert,Forest,Grassland,Swamp,Underdark,Urban",
            "48,Coastal,Desert,Forest,Grassland,Hill",
            "49,Forest,Grassland,Hill",
            "50,Coastal,Grassland,Mountain",
            "51,Grassland,Urban",
            "52,Forest,Grassland,Hill",
            "53,Forest",
            "54,Forest",
            "55,Swamp,Urban",
            "56,Grassland,Hill,Mountain",
            "57,Underwater",
            "58,Forest,Grassland,Urban",
            "59,Underwater",
            "60,Urban",
            "61,Arctic,Forest,Hill",
            "62,Forest,Hill",
            "63,Coastal,Grassland,Hill,Mountain",
            "64,Desert,Forest,Grassland,Hill",
            "65,Underwater",
            "66,Desert,Forest,Swamp,Underdark,Urban",
            "67,Coastal,Desert,Forest,Swamp,Underdark",
            "68,Desert,Grassland",
            "69,Desert,Grassland,Hill,Mountain",
            "70,Forest,Grassland",
            "71,Grassland",
            "72,Forest,Grassland,Hill",
            "73,Desert,Forest,Swamp,Underdark,Underwater",
            "74,Forest,Grassland,Hill,Mountain",
            "75,Underwater",
            "76,Coastal,Underwater",
            "77,Arctic,Underdark",
            "78,Grassland",
            "79,Arctic,Mountain",
            "80,Grassland",
            "81,Desert",
            "82,Underwater",
            "83,Grassland",
            "84,Swamp",
            "85,Underwater",
            "86,Grassland",
            "87,Arctic",
            "88,Forest",
            "89,Grassland",
            "90,Desert,Mountain",
            "91,Underdark",
            "92,Desert",
            "93,Coastal,Swamp,Underwater",

        };
    }
}
