using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DnDSidekick.Data.InitialData
{
    public static class MonsterAlignmentsInitialData
    {
        public static readonly string[] DataSeed =
        {
            "1,Unaligned",
            "2,Unaligned",
            "3,Unaligned",
            "4,Unaligned",
            "5,Unaligned",
            "6,Unaligned",
            "7,Unaligned",
            "8,Unaligned",
            "9,Unaligned",
            "10,Unaligned",
            "11,Unaligned",
            "12,Unaligned",
            "13,Unaligned",
            "14,Unaligned",
            "15,Unaligned",
            "16,Unaligned",
            "17,Unaligned",
            "18,Unaligned",
            "19,Unaligned",
            "20,Unaligned",
            "21,Unaligned",
            "22,Unaligned",
            "23,Unaligned",
            "24,Unaligned",
            "25,Unaligned",
            "26,Unaligned",
            "27,Unaligned",
            "28,Unaligned",
            "29,Unaligned",
            "30,Unaligned",
            "31,Unaligned",
            "32,Unaligned",
            "33,Unaligned",
            "34,Unaligned",
            "35,Unaligned",
            "36,Unaligned",
            "37,Unaligned",
            "38,Unaligned",
            "39,Unaligned",
            "40,Unaligned",
            "41,Unaligned",
            "42,Unaligned",
            "43,Unaligned",
            "44,Unaligned",
            "45,Unaligned",
            "46,Neutral",
            "47,Unaligned",
            "48,Unaligned",
            "49,Unaligned",
            "50,Unaligned",
            "51,Unaligned",
            "52,Unaligned",
            "53,Unaligned",
            "54,Unaligned",
            "55,Unaligned",
            "56,Unaligned",
            "57,Unaligned",
            "58,Unaligned",
            "59,Unaligned",
            "60,Unaligned",
            "61,Unaligned",
            "62,Unaligned",
            "63,Neutral Good",
            "64,Unaligned",
            "65,Unaligned",
            "66,Unaligned",
            "67,Unaligned",
            "68,Neutral Evil",
            "69,Unaligned",
            "70,Unaligned",
            "71,Unaligned",
            "72,Unaligned",
            "73,Unaligned",
            "74,Unaligned",
            "75,Unaligned",
            "76,Unaligned",
            "77,Unaligned",
            "78,Unaligned",
            "79,Unaligned",
            "80,Unaligned",
            "81,Unaligned",
            "82,Unaligned",
            "83,Unaligned",
            "84,Unaligned",
            "85,Unaligned",
            "86,Unaligned",
            "87,Unaligned",
            "88,Unaligned",
            "89,Unaligned",
            "90,Neutral",
            "91,Neutral",
            "92,Neutral",
            "93,Neutral"
        };
    }
}
